### ISSUE TITLE
Decouple UI Components from TIKI SDK

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-flutter#260]
Currently, the UI components in TIKI SDK are tightly coupled with the SDK, making it difficult for developers to use them without the SDK Theme. This can create a dependency issue for developers who may not want to use all the SDK pre-built UIs.

### Proposed Solution
To make the UI components more flexible and reusable, we need to decouple them from the TIKI SDK. This can be achieved by ensuring that each component receives all the necessary parameters through initialization parameters. These parameters should include all colors and styles that are currently used from the TIKI SDK Theme and any necessary methods that are called from TIKI SDK. 

### Expected Result
Once the UI components are decoupled from the TIKI SDK, developers should be able to use them without any reference to the TIKI SDK. This will allow for more flexibility and easier integration with other projects.

### Tasks
- [x] Identify all the necessary parameters for each UI component.
- [x] Modify the initialization parameters of each component to include all necessary parameters.
- [x] Ensure that the UI components work properly with or without the TIKI SDK.
- [x] Update the documentation to reflect the changes made to the UI components.

### Additional Information
- Decoupling the UI components from the TIKI SDK will make them more flexible and reusable.
- This change will make it easier for developers to use the UI components without depending on the TIKI SDK.

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/236221312-d58bfc2a-34ec-47ae-adf0-ced0f8f2d505.png)
